### ISSUE TITLE
Blind consumer on credentials/tcp lost

### ISSUE THREAD

**Issue by Freyskeyd** [Geal/lapin#44]
Hi,

I tried to connect to one of my rabbitmq, it allow only one user with credentials.
I tried to define wrong credentials and the consumer process is still working, I clearly see in rabbitmq logs:

```log
=INFO REPORT==== 26-Apr-2017::09:44:02 ===
accepting AMQP connection <0.1532.0> (172.17.0.1:37890 -> 172.17.0.2:5672)

=ERROR REPORT==== 26-Apr-2017::09:44:02 ===
Error on AMQP connection <0.1532.0> (172.17.0.1:37890 -> 172.17.0.2:5672, state: starting):
PLAIN login refused: user 'myusername' - invalid credentials
```
If I fix credentials but I don't update the `vhost`:
```log
=INFO REPORT==== 26-Apr-2017::09:50:06 ===
accepting AMQP connection <0.1345.0> (172.17.0.1:37892 -> 172.17.0.2:5672)

=ERROR REPORT==== 26-Apr-2017::09:50:06 ===
Error on AMQP connection <0.1345.0> (172.17.0.1:37892 -> 172.17.0.2:5672, user: 'iadvize', state: opening):
access to vhost '/' refused for user 'myusername'
```

Is the consumer process blind to credentials failing?

Another problem, if I kill my rabbitmq, the consumer is still running.

Let me know if you want more details.

**Comment by Keruspe** [comment]
Hi,

This should be fixed in #42

**Comment by Geal** [comment]
great

**Comment by Freyskeyd** [comment]
I just tried with recently merged PR but it's not fixed.

cc @Keruspe @Geal

**Comment by Freyskeyd** [comment]
Here's a tracelog:

```log
➜  lapintest master ✗ RUST_LOG=lapin=trace cargo run --example connect
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/connect`
TRACE:lapin_futures::transport: sink start send
TRACE:lapin_futures::transport: will encode and write frame: ProtocolHeader
TRACE:lapin_futures::transport: serialized frame: 8 bytes
TRACE:lapin_futures::transport: sink poll_complete
TRACE:lapin_futures::transport: stream poll
TRACE:lapin_futures::transport: upstream poll gave NotReady
TRACE:lapin_futures::transport: pre-poll
DEBUG:lapin_futures::transport: AMQPTransportConnector poll transport is none? false
TRACE:lapin_futures::transport: stream poll
TRACE:lapin_futures::transport: upstream poll gave NotReady
DEBUG:lapin_futures::transport: conn state: Connecting(SentProtocolHeader)
TRACE:lapin_futures::transport: waiting before poll
TRACE:lapin_futures::transport: stream poll
TRACE:lapin_futures::transport: upstream poll gave NotReady
TRACE:lapin_futures::transport: post-poll
DEBUG:lapin_futures::transport: AMQPTransportConnector poll transport is none? false
TRACE:lapin_futures::transport: stream poll
TRACE:lapin_futures::transport: upstream poll gave NotReady
DEBUG:lapin_futures::transport: conn state: Connecting(SentProtocolHeader)
TRACE:lapin_futures::transport: waiting before poll
TRACE:lapin_futures::transport: stream poll
TRACE:lapin_futures::transport: upstream poll gave NotReady
DEBUG:lapin_futures::transport: AMQPTransportConnector poll transport is none? false
TRACE:lapin_futures::transport: stream poll
TRACE:lapin_futures::transport: decoded frame: Method(0, Connection(Start(Start { version_major: 0, version_minor: 9, server_properties: {"capabilities": FieldTable({"authentication_failure_close": Boolean(true), "basic.nack": Boolean(true), "connection.blocked": Boolean(true), "consumer_cancel_notify": Boolean(true), "consumer_priorities": Boolean(true), "direct_reply_to": Boolean(true), "exchange_exchange_bindings": Boolean(true), "per_consumer_qos": Boolean(true), "publisher_confirms": Boolean(true)}), "cluster_name": LongString("rabbit@c831ff2a0c9f"), "copyright": LongString("Copyright (C) 2007-2016 Pivotal Software, Inc."), "information": LongString("Licensed under the MPL.  See http://www.rabbitmq.com/"), "platform": LongString("Erlang/OTP"), "product": LongString("RabbitMQ"), "version": LongString("3.6.6")}, mechanisms: "PLAIN AMQPLAIN", locales: "en_US" })))
TRACE:lapin_futures::transport: upstream poll gave frame: Method(0, Connection(Start(Start { version_major: 0, version_minor: 9, server_properties: {"capabilities": FieldTable({"authentication_failure_close": Boolean(true), "basic.nack": Boolean(true), "connection.blocked": Boolean(true), "consumer_cancel_notify": Boolean(true), "consumer_priorities": Boolean(true), "direct_reply_to": Boolean(true), "exchange_exchange_bindings": Boolean(true), "per_consumer_qos": Boolean(true), "publisher_confirms": Boolean(true)}), "cluster_name": LongString("rabbit@c831ff2a0c9f"), "copyright": LongString("Copyright (C) 2007-2016 Pivotal Software, Inc."), "information": LongString("Licensed under the MPL.  See http://www.rabbitmq.com/"), "platform": LongString("Erlang/OTP"), "product": LongString("RabbitMQ"), "version": LongString("3.6.6")}, mechanisms: "PLAIN AMQPLAIN", locales: "en_US" })))
TRACE:lapin_async::connection: will handle frame: Method(0, Connection(Start(Start { version_major: 0, version_minor: 9, server_properties: {"capabilities": FieldTable({"authentication_failure_close": Boolean(true), "basic.nack": Boolean(true), "connection.blocked": Boolean(true), "consumer_cancel_notify": Boolean(true), "consumer_priorities": Boolean(true), "direct_reply_to": Boolean(true), "exchange_exchange_bindings": Boolean(true), "per_consumer_qos": Boolean(true), "publisher_confirms": Boolean(true)}), "cluster_name": LongString("rabbit@c831ff2a0c9f"), "copyright": LongString("Copyright (C) 2007-2016 Pivotal Software, Inc."), "information": LongString("Licensed under the MPL.  See http://www.rabbitmq.com/"), "platform": LongString("Erlang/OTP"), "product": LongString("RabbitMQ"), "version": LongString("3.6.6")}, mechanisms: "PLAIN AMQPLAIN", locales: "en_US" })))
TRACE:lapin_async::connection: Server sent Connection::Start: Start { version_major: 0, version_minor: 9, server_properties: {"capabilities": FieldTable({"authentication_failure_close": Boolean(true), "basic.nack": Boolean(true), "connection.blocked": Boolean(true), "consumer_cancel_notify": Boolean(true), "consumer_priorities": Boolean(true), "direct_reply_to": Boolean(true), "exchange_exchange_bindings": Boolean(true), "per_consumer_qos": Boolean(true), "publisher_confirms": Boolean(true)}), "cluster_name": LongString("rabbit@c831ff2a0c9f"), "copyright": LongString("Copyright (C) 2007-2016 Pivotal Software, Inc."), "information": LongString("Licensed under the MPL.  See http://www.rabbitmq.com/"), "platform": LongString("Erlang/OTP"), "product": LongString("RabbitMQ"), "version": LongString("3.6.6")}, mechanisms: "PLAIN AMQPLAIN", locales: "en_US" }
DEBUG:lapin_async::connection: client sending Connection::StartOk: Connection(StartOk(StartOk { client_properties: {"product": LongString("lapin")}, mechanism: "PLAIN", response: "\u{0} myusername\u{0}guest", locale: "en_US" }))
TRACE:lapin_futures::transport: sink start send
TRACE:lapin_futures::transport: will encode and write frame: Method(0, Connection(StartOk(StartOk { client_properties: {"product": LongString("lapin")}, mechanism: "PLAIN", response: "\u{0} myusername\u{0}guest", locale: "en_US" })))
TRACE:lapin_futures::transport: serialized frame: 64 bytes
TRACE:lapin_futures::transport: sink poll_complete
TRACE:lapin_futures::transport: stream poll
TRACE:lapin_futures::transport: upstream poll gave NotReady
DEBUG:lapin_futures::transport: conn state: Connecting(SentStartOk)
TRACE:lapin_futures::transport: waiting before poll
TRACE:lapin_futures::transport: stream poll
TRACE:lapin_futures::transport: upstream poll gave NotReady
DEBUG:lapin_futures::transport: AMQPTransportConnector poll transport is none? false
TRACE:lapin_futures::transport: stream poll
ERROR:lapin_futures::transport: upstream poll gave Ready(None)
DEBUG:lapin_futures::transport: conn state: Connecting(SentStartOk)
TRACE:lapin_futures::transport: waiting before poll
TRACE:lapin_futures::transport: stream poll
ERROR:lapin_futures::transport: upstream poll gave Ready(None)
DEBUG:lapin_futures::transport: AMQPTransportConnector poll transport is none? false
TRACE:lapin_futures::transport: stream poll
TRACE:lapin_futures::transport: Sending heartbeat
TRACE:lapin_futures::transport: sink start send
TRACE:lapin_futures::transport: will encode and write frame: Heartbeat(0)
TRACE:lapin_futures::transport: serialized frame: 8 bytes
TRACE:lapin_futures::transport: sink poll_complete
ERROR:lapin_futures::transport: upstream poll gave Ready(None)
DEBUG:lapin_futures::transport: conn state: Connecting(SentStartOk)
TRACE:lapin_futures::transport: waiting before poll
TRACE:lapin_futures::transport: stream poll
ERROR:lapin_futures::transport: upstream poll gave Ready(None)
```

**Comment by Freyskeyd** [comment]
and Rabbitmq Log:

```log
=INFO REPORT==== 26-Apr-2017::18:12:45 ===
accepting AMQP connection <0.5507.0> (172.17.0.1:52018 -> 172.17.0.2:5672)

=ERROR REPORT==== 26-Apr-2017::18:12:45 ===
Error on AMQP connection <0.5507.0> (172.17.0.1:52018 -> 172.17.0.2:5672, state: starting):
PLAIN login refused: user 'myusername' - invalid credentials

```

**Comment by Keruspe** [comment]
That's weird, with the current master (with the PR merged) I get that when forcing wrong credentials in the client example:

```
TRACE:lapin_futures::transport: upstream poll gave NotReady
DEBUG:lapin_futures::transport: conn state: Connecting(SentStartOk)
TRACE:lapin_futures::transport: waiting before poll
TRACE:lapin_futures::transport: stream poll
DEBUG:tokio_core::reactor: consuming notification queue
DEBUG:tokio_core::reactor: scheduling direction for: 0
TRACE:lapin_futures::transport: upstream poll gave NotReady
DEBUG:tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 4325 }
DEBUG:tokio_core::reactor: loop time - Instant { tv_sec: 31267, tv_nsec: 955408760 }
DEBUG:tokio_core::reactor: loop process - 0 events, Duration { secs: 0, nanos: 9205 }
DEBUG:tokio_core::reactor: loop poll - Duration { secs: 3, nanos: 1143610 }
DEBUG:tokio_core::reactor: loop time - Instant { tv_sec: 31270, tv_nsec: 956565064 }
TRACE:tokio_core::reactor: event Ready {Readable | Writable | Error | Hup} Token(2)
DEBUG:tokio_core::reactor: notifying a task handle
DEBUG:tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 65915 }
DEBUG:tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 10413 }
DEBUG:tokio_core::reactor: loop time - Instant { tv_sec: 31270, tv_nsec: 956646642 }
TRACE:tokio_core::reactor: event Ready {Readable} Token(1)
DEBUG:tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 16311 }
DEBUG:lapin_futures::transport: AMQPTransportConnector poll transport is none? false
TRACE:lapin_futures::transport: stream poll
ERROR:lapin_futures::transport: upstream poll gave error: Error { repr: Os { code: 104, message: "Connection reset by peer" } }
DEBUG:tokio_core::reactor: consuming notification queue
DEBUG:tokio_core::reactor: dropping I/O source: 0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 104, message: "Connection reset by peer" } }', src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

With that in rabbitmq too

```
=INFO REPORT==== 26-Apr-2017::20:00:48 ===
accepting AMQP connection <0.532.0> (127.0.0.1:40646 -> 127.0.0.1:5672)

=ERROR REPORT==== 26-Apr-2017::20:00:48 ===
Error on AMQP connection <0.532.0> (127.0.0.1:40646 -> 127.0.0.1:5672, state: starting):
PLAIN login refused: user 'guest' - invalid credentials
```

**Comment by Freyskeyd** [comment]
how I reproduce the bug:
```bash
$ docker run -d --hostname my-rabbit  -p 5672:5672 --name some-rabbit rabbitmq:3
```

Updating `examples/client.rs` in `futures` with: 
```rust
  let opts = ConnectionOptions {
    password:"wrong".into(),
    ..ConnectionOptions::default()
  };
```

```bash
➜  lapin/futures master ✗ RUST_LOG=lapin=trace cargo run --example client
   Compiling lapin-futures v0.8.0 (file:///Users/Simon/work/perso/lapin/futures)
    Finished dev [unoptimized + debuginfo] target(s) in 5.14 secs
     Running `/Users/Simon/work/perso/lapin/target/debug/examples/client`
TRACE:lapin_futures::transport: sink start send
TRACE:lapin_futures::transport: will encode and write frame: ProtocolHeader
TRACE:lapin_futures::transport: serialized frame: 8 bytes
TRACE:lapin_futures::transport: sink poll_complete
TRACE:lapin_futures::transport: stream poll
TRACE:lapin_futures::transport: upstream poll gave NotReady
TRACE:lapin_futures::transport: pre-poll
DEBUG:lapin_futures::transport: AMQPTransportConnector poll transport is none? false
TRACE:lapin_futures::transport: stream poll
TRACE:lapin_futures::transport: upstream poll gave NotReady
DEBUG:lapin_futures::transport: conn state: Connecting(SentProtocolHeader)
TRACE:lapin_futures::transport: waiting before poll
TRACE:lapin_futures::transport: stream poll
TRACE:lapin_futures::transport: upstream poll gave NotReady
TRACE:lapin_futures::transport: post-poll
DEBUG:lapin_futures::transport: AMQPTransportConnector poll transport is none? false
TRACE:lapin_futures::transport: stream poll
TRACE:lapin_futures::transport: upstream poll gave NotReady
DEBUG:lapin_futures::transport: conn state: Connecting(SentProtocolHeader)
TRACE:lapin_futures::transport: waiting before poll
TRACE:lapin_futures::transport: stream poll
TRACE:lapin_futures::transport: upstream poll gave NotReady
DEBUG:lapin_futures::transport: AMQPTransportConnector poll transport is none? false
TRACE:lapin_futures::transport: stream poll
TRACE:lapin_futures::transport: decoded frame: Method(0, Connection(Start(Start { version_major: 0, version_minor: 9, server_properties: {"capabilities": FieldTable({"authentication_failure_close": Boolean(true), "basic.nack": Boolean(true), "connection.blocked": Boolean(true), "consumer_cancel_notify": Boolean(true), "consumer_priorities": Boolean(true), "direct_reply_to": Boolean(true), "exchange_exchange_bindings": Boolean(true), "per_consumer_qos": Boolean(true), "publisher_confirms": Boolean(true)}), "cluster_name": LongString("rabbit@my-rabbit"), "copyright": LongString("Copyright (C) 2007-2016 Pivotal Software, Inc."), "information": LongString("Licensed under the MPL.  See http://www.rabbitmq.com/"), "platform": LongString("Erlang/OTP"), "product": LongString("RabbitMQ"), "version": LongString("3.6.9")}, mechanisms: "AMQPLAIN PLAIN", locales: "en_US" })))
TRACE:lapin_futures::transport: upstream poll gave frame: Method(0, Connection(Start(Start { version_major: 0, version_minor: 9, server_properties: {"capabilities": FieldTable({"authentication_failure_close": Boolean(true), "basic.nack": Boolean(true), "connection.blocked": Boolean(true), "consumer_cancel_notify": Boolean(true), "consumer_priorities": Boolean(true), "direct_reply_to": Boolean(true), "exchange_exchange_bindings": Boolean(true), "per_consumer_qos": Boolean(true), "publisher_confirms": Boolean(true)}), "cluster_name": LongString("rabbit@my-rabbit"), "copyright": LongString("Copyright (C) 2007-2016 Pivotal Software, Inc."), "information": LongString("Licensed under the MPL.  See http://www.rabbitmq.com/"), "platform": LongString("Erlang/OTP"), "product": LongString("RabbitMQ"), "version": LongString("3.6.9")}, mechanisms: "AMQPLAIN PLAIN", locales: "en_US" })))
TRACE:lapin_async::connection: will handle frame: Method(0, Connection(Start(Start { version_major: 0, version_minor: 9, server_properties: {"capabilities": FieldTable({"authentication_failure_close": Boolean(true), "basic.nack": Boolean(true), "connection.blocked": Boolean(true), "consumer_cancel_notify": Boolean(true), "consumer_priorities": Boolean(true), "direct_reply_to": Boolean(true), "exchange_exchange_bindings": Boolean(true), "per_consumer_qos": Boolean(true), "publisher_confirms": Boolean(true)}), "cluster_name": LongString("rabbit@my-rabbit"), "copyright": LongString("Copyright (C) 2007-2016 Pivotal Software, Inc."), "information": LongString("Licensed under the MPL.  See http://www.rabbitmq.com/"), "platform": LongString("Erlang/OTP"), "product": LongString("RabbitMQ"), "version": LongString("3.6.9")}, mechanisms: "AMQPLAIN PLAIN", locales: "en_US" })))
TRACE:lapin_async::connection: Server sent Connection::Start: Start { version_major: 0, version_minor: 9, server_properties: {"capabilities": FieldTable({"authentication_failure_close": Boolean(true), "basic.nack": Boolean(true), "connection.blocked": Boolean(true), "consumer_cancel_notify": Boolean(true), "consumer_priorities": Boolean(true), "direct_reply_to": Boolean(true), "exchange_exchange_bindings": Boolean(true), "per_consumer_qos": Boolean(true), "publisher_confirms": Boolean(true)}), "cluster_name": LongString("rabbit@my-rabbit"), "copyright": LongString("Copyright (C) 2007-2016 Pivotal Software, Inc."), "information": LongString("Licensed under the MPL.  See http://www.rabbitmq.com/"), "platform": LongString("Erlang/OTP"), "product": LongString("RabbitMQ"), "version": LongString("3.6.9")}, mechanisms: "AMQPLAIN PLAIN", locales: "en_US" }
DEBUG:lapin_async::connection: client sending Connection::StartOk: Connection(StartOk(StartOk { client_properties: {"product": LongString("lapin")}, mechanism: "PLAIN", response: "\u{0}guest\u{0}wrong", locale: "en_US" }))
TRACE:lapin_futures::transport: sink start send
TRACE:lapin_futures::transport: will encode and write frame: Method(0, Connection(StartOk(StartOk { client_properties: {"product": LongString("lapin")}, mechanism: "PLAIN", response: "\u{0}guest\u{0}wrong", locale: "en_US" })))
TRACE:lapin_futures::transport: serialized frame: 62 bytes
TRACE:lapin_futures::transport: sink poll_complete
TRACE:lapin_futures::transport: stream poll
TRACE:lapin_futures::transport: upstream poll gave NotReady
DEBUG:lapin_futures::transport: conn state: Connecting(SentStartOk)
TRACE:lapin_futures::transport: waiting before poll
TRACE:lapin_futures::transport: stream poll
TRACE:lapin_futures::transport: upstream poll gave NotReady
DEBUG:lapin_futures::transport: AMQPTransportConnector poll transport is none? false
TRACE:lapin_futures::transport: stream poll
ERROR:lapin_futures::transport: upstream poll gave Ready(None)
DEBUG:lapin_futures::transport: conn state: Connecting(SentStartOk)
TRACE:lapin_futures::transport: waiting before poll
TRACE:lapin_futures::transport: stream poll
ERROR:lapin_futures::transport: upstream poll gave Ready(None)
```
